# apiVersion: v1
# kind: Service
# metadata:
  # name: ns2-dt-service
  # # for easy reference later on
  # labels:
    # pilot: sm
    # ns: ns2
    # cnf: dt
    # cdu: dt
# spec:
  # ports:
    # - name: dt
      # port: 15001
    # - name: samba139
      # port: 139
    # - name: samba445
      # port: 445
    # # can't mix TCP and UDP ports in a single LB service
    # - name: samba137udp
      # protocol: UDP
      # port: 137
    # - name: samba138udp
      # protocol: UDP
      # port: 138
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns2-dt-deployment
  labels:
    pilot: sm
    ns: ns2
    cnf: dt
    cdu: dt
spec:
  selector:
    # must match the labels of the template
    matchLabels:
      pilot: sm
      ns: ns2
      cnf: dt
      cdu: dt
  # the pod(s) to deploy = 1 CDU
  template:
    metadata:
      labels:
        pilot: sm
        ns: ns2
        cnf: dt
        cdu: dt
    spec:
      containers:
      - name: vnf-dt
        image: sonatanfv/vnf-dt:k8s
        imagePullPolicy: Always
