apiVersion: v1
kind: Service
metadata:
  name: ns2-mdc-service
  # for easy reference later on
  labels:
    pilot: sm
    ns: ns2
    cnf: mdc
    cdu: mdc
spec:
  # to which deployment does this service belong?
  selector:
    pilot: sm
    ns: ns2
    cnf: mdc
    cdu: mdc
  # this requires MetalLB (or another LB) to be installed and configured
  type: LoadBalancer
  ports:
    # don't need the UDP ports
    - name: samba139
      protocol: TCP
      port: 139
      nodePort: 139
    - name: samba445
      protocol: TCP
      port: 445
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns2-mdc-deployment
  labels:
    pilot: sm
    ns: ns2
    cnf: mdc
    cdu: mdc
spec:
  selector:
    # must match the labels of the template
    matchLabels:
      pilot: sm
      ns: ns2
      cnf: mdc
      cdu: mdc
  # the pod(s) to deploy = 1 CDU
  template:
    metadata:
      labels:
        pilot: sm
        ns: ns2
        cnf: mdc
        cdu: mdc
    spec:
      containers:
      - name: vnf-mdc
        image: sonatanfv/vnf-mdc:k8s
        imagePullPolicy: Always
        env:
        # this needs to be set by the SP dynamically!
        # we will change the var name to vendor.name.version.cdu_id
        - name: MQTT_BROKER_HOST
          value: ns1-cc-broker-service
        - name: MQTT_BROKER_PORT
          value: "1883"
