apiVersion: v1
kind: Service
metadata:
  name: ns1-eae-service
  # for easy reference later on
  labels:
    pilot: sm
    ns: ns1
    cnf: eae
    cdu: eae
spec:
  # to which deployment does this service belong?
  selector:
    pilot: sm
    ns: ns1
    cnf: eae
    cdu: eae
  type: NodePort
  ports:
    # cluster-internal access via port 3000, external via port 30000
    - name: grafana
      port: 3000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns1-eae-deployment
  labels:
    pilot: sm
    ns: ns1
    cnf: eae
    cdu: eae
spec:
  selector:
    # must match the labels of the template
    matchLabels:
      pilot: sm
      ns: ns1
      cnf: eae
      cdu: eae
  # the pod(s) to deploy = 1 CDU
  template:
    metadata:
      labels:
        pilot: sm
        ns: ns1
        cnf: eae
        cdu: eae
    spec:
      containers:
      - name: vnf-eae
        image: sonatanfv/vnf-eae:k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
