version: '0.5'
descriptor_extension: yml
uuid: 722f27bb-8c1d-4511-a189-e1f14a4502de
package:
  version: '0.1'
  name: 5gtango-smp-sfelk
  vendor: eu.5gtango
  maintainer: ALB, sm-pilot@5gtango.pt
  description: SFELK - enhanced IDPS
files:
- path: tng_smp_vnfd_sf.yml
  tags:
  - eu.5gtango
  type: application/vnd.5gtango.vnfd
- path: tng_smp_vnfd_elk.yml
  tags:
  - eu.5gtango
  type: application/vnd.5gtango.vnfd
