version: '3'

services:

  haproxy:
    image: "registry.sonata-nfv.eu:5000/tng-haproxy"
    networks:
      - default
    ports:
     - "80:80"
     - "443:443"

networks:
  default:
    external:
      name: tango

