apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kube-f.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: filebeat
    name: filebeat
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: filebeat
      spec:
        containers:
        - env:
          - name: output.logstash.hosts
            value: '["localhost:9200"]'
          - name: setup.kibana.host
            value: kibana:5601
          image: docker.elastic.co/beats/filebeat:6.6.0
          name: filebeat
          resources: {}
          volumeMounts:
          - mountPath: /usr/share/filebeat/data
            name: f-sdata
        restartPolicy: Always
        volumes:
        - name: f-sdata
          persistentVolumeClaim:
            claimName: f-sdata
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: f-sdata
    name: f-sdata
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}

