apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smp-dev
  name: filebeat-deployment
  labels:
    app: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: arocha/u16filebeat:6.6.0
        imagePullPolicy: IfNotPresent
#       ports:
#       - containerPort: 80
