apiVersion: v1
kind: Service
metadata:
  name: ns1
  labels:
    app: ns1
    pilot: sm
spec:
  selector:
    app: ns1
  # for single-node testing with microk8s; switch to "LoadBalancer" for production
  type: NodePort
  ports:
    - name: mqtt
      port: 1883
    # cluster-internal access via port 3000, external via port 30000
    - name: grafana
      port: 3000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-ns1-deployment
  labels:
    app: ns1
    pilot: sm
spec:
  selector:
    matchLabels:
      app: ns1
  template:
    metadata:
      labels:
        app: ns1
    spec:
      containers:
      - name: vnf-cc-broker
        image: sonatanfv/vnf-cc-broker:k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 1883
      - name: vnf-cc-processor
        image: sonatanfv/vnf-cc-processor:k8s
        imagePullPolicy: Always
      - name: vnf-eae
        image: sonatanfv/vnf-eae:k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        