---  
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-static-configfile
  #namespace: e-ids
  labels:
    pilot: sm
    ns: ns2
    cnf: logstash
data:
  beats2elastic.conf: | 
    input {
      beats {
        port => 5044
        #codec => "json"
        #type => "SuricataIDPS"
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        manage_template => false
        document_type => "%{[@metadata][type]}"
      }
      stdout { codec => rubydebug }
    }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    pilot: sm
    ns: ns2
    cnf: logstash
  #namespace: e-ids
spec:
  replicas: 1
  selector:
    matchLabels:
      pilot: sm
      ns: ns2
      cnf: logstash
  template:
    metadata:
      labels:
        pilot: sm
        ns: ns2
        cnf: logstash
    spec:
      volumes:
      - name: esdata
        emptyDir: {}
      - name: logstash-config
        configMap:  
          name: logstash-static-configfile
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.7.1
        imagePullPolicy: IfNotPresent
        #args: [
        #  "-vvv",
        #]
        env:
        - name: PIPELINE_WORKERS
          value: "2"
        - name: xpack.monitoring.enable
          value: "true"
        - name: xpack.monitoring.elasticsearch.hosts
          value: "http://elasticsearch:9200"
        ports:
        - containerPort: 5044
        - containerPort: 9600
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline
          name: logstash-config
      dnsPolicy: ClusterFirst # service.namespace.svc.cluster.local
      hostNetwork: false

---
kind: Service
apiVersion: v1
metadata:
  name: logstash
  labels:
    pilot: sm
    ns: ns2
    cnf: logstash
  #namespace: e-ids
spec:
  type: LoadBalancer
  selector:
    cnf: logstash
  ports:
  - name: l-5044
    protocol: TCP
    port: 5044
    targetPort: 5044
  - name: l-9600
    protocol: TCP
    port: 9600
    targetPort: 9600
  #clusterIP: 10.x.x.x
  #loadBalancerIP: 172.31.14.248-9 (ALB-PRD)
#status:
  #loadBalancer:
    #ingress:
    #- ip: 172.31.14.x
#https://kubernetes.io/docs/concepts/services-networking/#loadbalancer
 
