---
kind: ConfigMap
apiVersion: v1
metadata:
  name: suricata-static-configfile
  namespace: sm
  labels:
    pilot: sm
    ns: ns2
    cnf: ids
data:
  suricata.yaml: |
    outputs.console:
      enabled: true
    outputs.eve-logs:
      enabled: true
      filename: eve.json
      filetype: regular
      append: no
      types:
      - alert:
        metadata: yes
        tagged-packets: yes 
      - http:
        extended: yes
      - dns:
        query: yes
        answer: yes
      - tls:
        extended: yes
        - files:
          force-magic: no
          force-hash: [md5, sha256]
      - ssh
      - flow 
    outputs.files:
      enabled: true
      filename: /var/log/suricata/suricata.log
      level: info


---  
kind: ConfigMap
apiVersion: v1
metadata:
  name: filebeat-static-configfile
  namespace: sm
  labels:
    pilot: sm
    ns: ns2
    cnf: ids
data:
  filebeat.yml: | 
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
      - /var/log/suricata/eve.json
    processors: 
    - add_host_metadata: ~ 
    - add_cloud_metadata: ~ 
    filebeat.config:
      modules:
        #strict.perms: false
        path: ${path.config}/modules.d/*.yml
        reload.enabled: true
    filebeat.modules:
    - module: suricata
    setup.dashboards:
      enabled: false
      #beat: filebeat
      #directory: build/kibana
    setup.template:
      #enabled: false
      #fields: "/usr/share/filebeat/fields.yml"
      settings.index.number_of_shards: 3
    setup.kibana:
      host: "kibana:32056"
    output.elasticsearch:
      enabled: false
      hosts: ["elasticsearch:32092"]
    output.logstash:
      enabled: true
      hosts: ["logstash:32044"]


---
apiVersion: v1
kind: Pod
metadata:
  namespace: sm
  name: ns2sf
  labels:
    pilot: sm
    ns: ns2
    cnf: ids
    name: ns2sf
spec:
  volumes:
  - name: suricata-logs
    emptyDir: {}
  - name: filebeat-config
    configMap:  
      name: filebeat-static-configfile
  containers:
  - name: suricata
    image: jasonish/suricata
    imagePullPolicy: IfNotPresent
    args: ["-i enp3s0"]
    volumeMounts:
    - name: suricata-logs
      mountPath: /var/log/suricata
    securityContext:
      privileged: true
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:6.7.0
    imagePullPolicy: IfNotPresent
    #command: ["/usr/share/filebeat/filebeat"]
    args: [
      #"setup", 
      #"--modules=suricata",
      "-e",
      "-c",
      "/usr/share/filebeat/config/filebeat.yml",
    ]
    volumeMounts:
    - name: suricata-logs
      mountPath: /var/log/suricata
    - name: filebeat-config
      mountPath: /usr/share/filebeat/config
    securityContext:
      privileged: false
  hostname: ns2sf
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
