---  
kind: ConfigMap
apiVersion: v1
metadata:
  name: filebeat-static-configfile
  namespace: smp-ns3
  labels:
    app: ns3f
data:
  filebeat.yml: | 
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
      - /var/log/suricata/eve.json
    filebeat.config.modules:
      strict.perms: false
      path: ${path.config}/modules.d/*.yml
      reload.enabled: true
    setup.dashboards:
      enabled: true
    setup.template:
      enabled: false
      fields: "/usr/share/filebeat/fields.yml"
      settings.index.number_of_shards: 3
    setup.kibana:
      host: "localhost:30056"
    output.elasticsearch:
      enabled: false
      hosts: [localhost:30092]
    output.logstash:
      enabled: true
      hosts: ["localhost:30044"]

---
apiVersion: v1
kind: Pod
metadata:
  namespace: smp-ns3
  name: ns3f
  labels:
    name: ns3f
spec:
  volumes:
  - name: suricata-logs
    emptyDir: {}
  - name: filebeat-config
    configMap:
    emptyDir: {}
#      name: filebeat-static-configfile
  containers:
  - name: filebeat

    image: docker.elastic.co/beats/filebeat:6.6.2
    imagePullPolicy: IfNotPresent

    volumeMounts:
    - name: suricata-logs
      mountPath: /usr/share/filebeat/logs/
    - name: filebeat-config
      mountPath: /usr/share/filebeat/config
    securityContext:
      privileged: false
  hostname: ns3f
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
