---
apiVersion: v1
kind: Pod # actually Deployment does not suppoprt hostNetwork
metadata:
  namespace: sm
  name: ns3sf
  labels:
    pilot: sm
    ns: ns3
    cnf: ids
    name: ns3sf
spec:
  volumes:
  - name: suricata-logs
    emptyDir: {}
  - name: filebeat-config
    configMap:  
      name: filebeat-static-configfile
  containers:
  - name: suricata
    image: jasonish/suricata
    imagePullPolicy: IfNotPresent
    args: ["-i enp3s0"]
    volumeMounts:
    - name: suricata-logs
      mountPath: /var/log/suricata
    securityContext:
      privileged: true
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:6.6.2
    imagePullPolicy: IfNotPresent
    #command: ["/usr/share/filebeat/filebeat"]
    args: [
      #"setup", 
      #"--modules=suricata",
      "-e",
      "-c",
      "/usr/share/filebeat/config/filebeat.yml",
    ]
    volumeMounts:
    - name: suricata-logs
      mountPath: /var/log/suricata
    - name: filebeat-config
      mountPath: /usr/share/filebeat/config
    securityContext:
      privileged: false
  hostname: ns3sf
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
