apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-deployment
  labels:
    app: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: arocha/u16filebeat
#       ports:
#       - containerPort: 80

