---
apiVersion: v1
kind: Pod
metadata:
  namespace: smp-dev
  name: ns3elk
  labels:
    name: ns3elk
spec:
  volumes:
  - name: esdata
    emptyDir: {}
#  hostAliases:
#  - ip: "127.0.0.1"
#    hostnames:
#    - "logstash.smp-dev.svc.cluster.local"
#    - "logstash"
#    hostnames:
#    - "ns3elk.smp-dev.svc.cluster.local"
#    - "elasticsearch"
#    hostnames:
#    - "kibana.smp-dev.svc.cluster.local"
#    - "kibana"
  containers:
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    imagePullPolicy: IfNotPresent
    env:
    - name: ES_JAVA_OPTS
      value: -Xms1g -Xmx1g
    - name: bootstrap.memory_lock
      value: "true"
    - name: discovery.type
      value: single-node
    ports:
    - containerPort: 9200 # for REST API
      protocol: TCP
    - containerPort: 9300 # for Nodes communication
      protocol: TCP
  - name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.1
    imagePullPolicy: IfNotPresent
    env:
    - name: elasticsearch
      value: http://ns3elk:9200
    - name: server.name
      value: localhost
    ports:
    - containerPort: 5601
  - name: logstash
    image: docker.elastic.co/logstash/logstash:6.6.1
    imagePullPolicy: IfNotPresent
    env:
    - name: PIPELINE_WORKERS
      value: '"2"'
    - name: xpack.monitoring.elasticsearch.url
      value: http://ns3elk:9200
    ports:
    - containerPort: 5044
    - containerPort: 9600
  hostname: ns3elk
  hostNetwork: false
  dnsPolicy: ClusterFirst
# dnsConfig:
#   nameservers:
#   - 8.8.8.8
#   - 9.9.9.9
#   searches:
#    - smp-dev.svc.cluster.local
#    - my.dns.search.suffix
#  subdomain: smp-dev


---
apiVersion: v1
kind: Pod
metadata:
  namespace: smp-dev
  name: ns3sf
  labels:
    name: ns3sf
spec:
  volumes:
  - name: suricata-logs
    emptyDir: {}
#  hostAliases:
#  - ip: "127.0.0.1"
#    hostnames:
#    - "logstash"
#    - "logstash.smp-dev.svc.cluster.local"
#    hostnames:
#    - "elasticsearch"
#    - "ns3elk.smp-dev.svc.cluster.local"
  containers:

  - name: suricata
    image: jasonish/suricata
    imagePullPolicy: IfNotPresent
    #args: ["-i enp3s0"]
    args: ["-i eth0"]
    volumeMounts:
    - name: suricata-logs
      mountPath: /var/log/suricata
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:6.6.2
    imagePullPolicy: IfNotPresent
    args: [
      "setup", 
      "-c", "/usr/share/filebeat/filebeat.yml",
      "-E", "setup.dashboards.enabled=true",
      "-E", "setup.kibana.host=ns3elk:5601",
      #"-E", "setup.template.enabled=false",
#      "-E", "output.elasticsearch.enabled=false",
#      "-E", "output.logstash.enabled=true",
#      "-E", "output.logstash.hosts=[logstash:5044]",
      "-E", "output.elasticsearch.enabled=true",
      "-E", "output.elasticsearch.hosts=[ns3elk:9200]",
      "-e",
      "&&",
      "filebeat",
      "modules", 
      "enable",
      "suricata"
    ]
    env:
    - name: output.logstash.hosts
      value: logstash:5044
    - name: output.elasticsearch.hosts
      value: ns3elk:9200
    - name: setup.kibana.host
      value: ns3elk:5601
    volumeMounts:
    - name: suricata-logs
      mountPath: /usr/share/filebeat/logs
  hostname: ns3sf
  hostNetwork: false
#  dnsPolicy: ClusterFirstWithHostNet
  dnsPolicy: ClusterFirst
#  dnsPolicy: "None"
#  dnsConfig:
#    nameservers:
#    - 8.8.8.8
#    - 9.9.9.9
#    searches:
#    - smp-dev.svc.cluster.local
#    - my.dns.search.suffix
#  subdomain: smp-dev


---
apiVersion: v1
kind: Service
metadata:
  namespace: smp-dev
  name: ns3elk
  labels:
    name: ns3elk
spec:
  ports:
  - port: 9200
    targetPort: 9200
    name: elasticsearch
  - port: 5601
    targetPort: 5601
    name: kibana
  - port: 5044
    targetPort: 5044
    name: logstash
  selector:
    name: ns3elk

---
apiVersion: v1
kind: Service
metadata:
  namespace: smp-dev
  name: ns3kib
  labels:
    name: ns3kib
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30056 
    name: kibana
  selector:
    name: ns3kib
