apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smp-dev
  name: suricata-ids
  labels:
    app: suricata-ids
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suricata-ids
  template:
    metadata:
      labels:
        app: suricata-ids
    spec:
      containers:
      - name: suricata-ids
        image: arocha/ce7suricata:4.1.2
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - /usr/sbin/suricata
          - -c
          - suricata.yaml
          - -s
          - signatures.rules
          - -i
          - eth0
#      - name: filebeat
#        image: arocha/u16filebeat:6.6.0
#        imagePullPolicy: IfNotPresent
