---
apiVersion: v1
kind: Pod
metadata:
  namespace: alb-prd
  name: ns3elk
  labels:
    name: ns3elk
spec:
  volumes:
  - name: esdata
    emptyDir: {}
  containers:
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    imagePullPolicy: IfNotPresent
    env:
    - name: ES_JAVA_OPTS
      value: -Xms1g -Xmx1g
    - name: bootstrap.memory_lock
      value: "true"
    - name: discovery.type
      value: single-node
    ports:
    - containerPort: 9200 # for REST API
      protocol: TCP
    - containerPort: 9300 # for Nodes communication
      protocol: TCP
  - name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.2
    imagePullPolicy: IfNotPresent
    env:
    - name: ELASTICSEARCH_HOSTS
      value: "http://localhost:9200"
    - name: SERVER_NAME
      value: "kibana"
    - name: XPACK_MONITORING_ENABLED 
      value: "true"
    ports:
    - containerPort: 5601
  - name: logstash
    image: docker.elastic.co/logstash/logstash:6.6.2
    imagePullPolicy: IfNotPresent
    env:
    - name: PIPELINE_WORKERS
      value: '"2"'
    - name: xpack.monitoring.elasticsearch.url
      value: http://localhost:9200
    ports:
    - containerPort: 5044
    - containerPort: 9600
  hostname: ns3elk
  hostNetwork: false
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 10.96.0.10 # Calico plugin
      - 10.240.144.10 # Flannel plugin
      - 8.8.8.8 # External name resolution
    searches:
      - alb-prd.svc.cluster.local
      - svc.cluster.local
    options:
      - name: ndots
        value: "2"
      - name: edns0

---
apiVersion: v1
kind: Pod
metadata:
  namespace: alb-prd
  name: ns3sf
  labels:
    name: ns3sf
spec:
  volumes:
  - name: suricata-logs
    emptyDir: {}
  containers:
  - name: suricata
    image: jasonish/suricata
    imagePullPolicy: IfNotPresent
    #args: ["-i enp3s0"]
    args: ["-i enp3s0"]
    volumeMounts:
    - name: suricata-logs
      mountPath: /var/log/suricata
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:6.6.2
    imagePullPolicy: IfNotPresent
    args: [
      "setup", 
      "-c", "/usr/share/filebeat/filebeat.yml",
      "-E", "setup.dashboards.enabled=true",
      "-E", "setup.kibana.host=localhost:30056",
      "-E", "setup.template.enabled=true",
      "-E", "output.elasticsearch.enabled=true",
#      "-E", "output.logstash.enabled=true",
#      "-E", "output.logstash.hosts=[logstash:5044]",
      "-E", "output.elasticsearch.enabled=true",
      "-E", "output.elasticsearch.hosts=[localhost:30092]",
      "-e",
#      "&&",
#      "filebeat",
#      "modules", 
#      "enable",
#      "suricata"
    ]
    env:
#    - name: output.logstash.hosts
#      value: localhost:30044
    - name: output.elasticsearch.hosts
      value: localhost:30092
    - name: setup.kibana.host
      value: localhost:30056
    volumeMounts:
    - name: suricata-logs
      mountPath: /usr/share/filebeat/logs
  hostname: ns3sf
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet


---
apiVersion: v1
kind: Service
metadata:
  namespace: alb-prd
  name: ns3l
  labels:
    name: ns3l
spec:
  type: NodePort
  ports:
  - port: 5044
    targetPort: 5044
    nodePort: 30044 
    #name: logstash
  selector:
    name: ns3l

---
apiVersion: v1
kind: Service
metadata:
  namespace: alb-prd
  name: ns3e
  labels:
    name: ns3e
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30092
    #name: elasticsearch
  selector:
    name: ns3e

---
apiVersion: v1
kind: Service
metadata:
  namespace: alb-prd
  name: ns3k
  labels:
    name: ns3k
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30056 
    #name: kibana
  selector:
    name: ns3k
