---  
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-static-configfile
  namespace: smp-ns3
  labels:
    app: ns3elk
data:
  beats2elastic.conf: | 
    input {
      beats {
        port => 5044
        #codec => json
        #type => "SuricataIDPS"
      }
    }
    filter {
      if [type] == "syslog" {
        grok {
          match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
          add_field => [ "received_at", "%{@timestamp}" ]
          add_field => [ "received_from", "%{host}" ]
        }
        syslog_pri { }
        date {
          match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
        }
      }
    }
    output {
      elasticsearch {
        hosts => ["http://localhost:9200"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        manage_template => false
        document_type => "%{[@metadata][type]}"
      }
      stdout { codec => rubydebug }
    }

---
apiVersion: v1
kind: Pod
metadata:
  namespace: smp-ns3
  name: ns3elk
  labels:
    name: ns3elk
spec:
  volumes:
  - name: esdata
    emptyDir: {}
  - name: logstash-hostdir
    hostPath:
      path: "/C/Users/arocha/git/tng-industrial-pilot/vnfs/ids-selk/l/pipeline"
  containers:
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    imagePullPolicy: IfNotPresent
    env:
    - name: ES_JAVA_OPTS
      value: -Xms1g -Xmx1g
    - name: bootstrap.memory_lock
      value: "true"
    - name: discovery.type
      value: single-node
    ports:
    - containerPort: 9200 # for REST API
      protocol: TCP
    - containerPort: 9300 # for Nodes communication
      protocol: TCP
  - name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.2
    imagePullPolicy: IfNotPresent
    env:
    - name: ELASTICSEARCH_HOSTS
      value: "http://localhost:9200"
    - name: SERVER_NAME
      value: "kibana"
    - name: XPACK_MONITORING_ENABLED 
      value: "true"
    ports:
    - containerPort: 5601
  - name: logstash
    image: docker.elastic.co/logstash/logstash:6.6.2
    imagePullPolicy: IfNotPresent
    env:
    - name: PIPELINE_WORKERS
      value: "2"
    - name: xpack.monitoring.elasticsearch.url
      value: http://localhost:9200
    ports:
    - containerPort: 5044
    - containerPort: 9600
    volumeMounts:
    - mountPath: /usr/share/logstash/pipeline
      name: logstash-config
  volumes:  
  - name: logstash-config
    configMap:  
      name: logstash-static-configfile  
  hostname: ns3elk
  hostNetwork: false
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 10.96.0.10 # Calico plugin
      - 10.240.144.10 # Flannel plugin
      - 8.8.8.8 # External name resolution
    searches:
      - smp-ns3.svc.cluster.local
      - svc.cluster.local
    options:
      - name: ndots
        value: "2"
      - name: edns0

---
apiVersion: v1
kind: Pod
metadata:
  namespace: smp-ns3
  name: ns3sf
  labels:
    name: ns3sf
spec:
  volumes:
  - name: suricata-logs
    emptyDir: {}
  containers:
  - name: suricata
    image: jasonish/suricata
    imagePullPolicy: IfNotPresent
    #args: ["-i enp3s0"]
    args: ["-i enp3s0"]
    volumeMounts:
    - name: suricata-logs
      mountPath: /var/log/suricata
    securityContext:
      privileged: true
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:6.6.2
    imagePullPolicy: IfNotPresent
    command: ["/usr/share/filebeat/filebeat"]
    args: [
 #     "setup", 
 #     "--template",
 #     "-E", "setup.template.enabled=false",
 #     "-E", "setup.template.fields=/usr/share/filebeat/fields.yml",
      #"-c", "/usr/share/filebeat/filebeat.yml",
      "-E", "setup.dashboards.enabled=true",
      "-E", "setup.kibana.host=localhost:30056",
      "-E", "output.elasticsearch.enabled=false",
#      "-E", "output.elasticsearch.hosts=[localhost:30092]",
      "-E", "output.logstash.enabled=true",
      "-E", "output.logstash.hosts=[localhost:30044]",
      "-e",
    ]
    volumeMounts:
    - name: suricata-logs
      mountPath: /usr/share/filebeat/logs
    securityContext:
      privileged: true
  hostname: ns3sf
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet


---
apiVersion: v1
kind: Service
metadata:
  namespace: smp-ns3
  name: ns3l
  labels:
    name: ns3l
spec:
  type: NodePort
  ports:
  - port: 5044
    targetPort: 5044
    nodePort: 30044 
    name: logstash-beats-inputs
  - port: 9600
    targetPort: 9600
    nodePort: 30096
    name: logstash-api-endpoint
  selector:
    name: ns3elk

---
apiVersion: v1
kind: Service
metadata:
  namespace: smp-ns3
  name: ns3e
  labels:
    name: ns3e
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30092
    #name: elasticsearch
  selector:
    name: ns3elk

---
apiVersion: v1
kind: Service
metadata:
  namespace: smp-ns3
  name: ns3k
  labels:
    name: ns3k
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30056 
    #name: kibana
  selector:
    name: ns3elk
